<?php $session = new Zend_Session_Namespace('data');?>

<!-- Heading -->
<div id="heading" >
	<h1>CEK DENDA</h1>
</div>

<!-- Main -->
<section id="main" class="wrapper">
<div class="inner">
    <div class="content">

	<!-- Elements -->
	<div class="row">
						
							
				
						
        	<form method="get" action="<?php echo $this->url(array('controller'=>'cek', 'action'=>'konfirmasi')); ?>" class="mx-auto" >
        									
        	   <div class="row gtr-uniform">
        	       
        			<div class="col-sm-12"><div class="form-group"><h4>Masukkan nomor Virtual Account</h4></div></div>
        						
        						
        									
        											
        											
            		<div class="col-sm-12">
            			<div class="form-group">
                              <label class="sr-only">Nomor Virtual Account Pelanggan</label>
                              <input type="number" name="nova" class="form-control" placeholder="Nomor VA" required="required" autocomplete="off">
                        </div>
                           
                            
                        <ul class="actions">
            			     <li><input type="submit" value="Submit" class="primary" /></li>
            	             <li><input type="reset" value="Reset" /></li>
            		    </ul>
            		</div>
            		
            		<div class="col-sm-12"><div class="form-group"></div></div>
        											
        						
        		</div>
        	</form>
									

							
								
								

							
	</div>
	</div>
</div>
</section>



		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/browser.min.js"></script>
			<script src="assets/js/breakpoints.min.js"></script>
			<script src="assets/js/util.js"></script>
			<script src="assets/js/main.js"></script>

		
